apiVersion: apps/v1
kind: Deployment
metadata:
  name: notion-telegram-bot-js
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notion-telegram-bot-js
  template:
    metadata:
      labels:
        app: notion-telegram-bot-js
    spec:
      containers:
        - name: app
          image: learnk8s/notion-telegram-bot-js:1.0.0
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
          imagePullPolicy: Always
