version: "3.9"

services:
  telegram-bot-test:
    image: notion-utils-js
    container_name: notion-telegram-bot-test
    # network_mode: host
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      NODE_ENV: test
    env_file:
      - .env.test
    # command: ["node", "./dist/telegram-bot.js"]
    command: ["ts-node", "./src/telegram-bot.ts"]
    volumes:
      - ./src/scrape/scrapeItem.json:/tmp/scrapeItem.json

  add-content-service-test:
    image: notion-utils-js
    container_name: add-content-service-test
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      NODE_ENV: test
    env_file:
      - .env.test
    command: ["node", "./dist/add-content-service.js"]
    volumes:
      - ./src/scrape/scrapeItem.json:/tmp/scrapeItem.json

  postgres-test:
    image: postgres:15.1-alpine
    container_name: notion-telegram-postgres-test
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    env_file:
      - dbcredentials.env
    volumes:
      - /data/notion-telegram/test:/var/lib/postgresql/data
