version: "3.4"

services:
  telegram-bot:
    image: telegram-bot
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      NODE_ENV: test
    env_file:
      - .env.test
    volumes:
      - ./src/scrape/scrapeItem.json:/tmp/scrapeItem.json

  postgres:
    image: postgres:15.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    env_file:
      - dbcredentials.env
    volumes:
      - /data/notion-telegram:/var/lib/postgresql/data
# volumes:
#   db:
#     driver: local
