version: "3.4"

services:
  # notionutils:
  #   image: notionutils
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   environment:
  #     NODE_ENV: production
  #   env_file:
  #     - .env
  #   command: node ./dist/index.js

  telegram-bot:
    image: telegram-bot
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      NODE_ENV: production
    env_file:
      - .env
    volumes:
      - ./src/scrape/scrapeItem.json:/tmp/scrapeItem.json
    # command: node ./dist/telegram-bot.js

  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
