version: "3.4"

services:
  notionutils:
    image: notionutils
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    env_file:
      - .env
