version: "3.9"

services:
  telegram-bot-prod:
    image: notion-utils-js
    container_name: notion-telegram-bot-prod
    # network_mode: host
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      NODE_ENV: production
    env_file:
      # - .env
      - .env.prod
    # command: ["node", "./dist/telegram-bot.js"]
    # command: ["ts-node", "./src/telegram-bot.js"]
    volumes:
      - ./src/scrape/scrapeItem.json:/tmp/scrapeItem.json

  add-content-service-prod:
    image: notion-utils-js
    container_name: add-content-service-prod
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      NODE_ENV: production
    env_file:
      - .env.prod
    command: ["node", "./dist/add-content-service.js"]
    volumes:
      - ./src/scrape/scrapeItem.json:/tmp/scrapeItem.json

  postgres-prod:
    image: postgres:15.1-alpine
    container_name: notion-telegram-postgres-prod
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5430:5432"
    env_file:
      - dbcredentials.env
    volumes:
      - /data/notion-telegram/prod:/var/lib/postgresql/data
