name: Create pull request

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: ["test"]

# env:
#   TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
#   TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
#   TELEGRAM_SESSION_KEY: ${{ secrets.TELEGRAM_SESSION_KEY }}
#   TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
#   NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
#   NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create pull request
        run: |
          gh label create -f ready-to-merge
          gh pr create -B main -H test -l ready-to-merge --title 'Merge test into main' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: auto merge pull request
      #   run: |
      #     # get last pull-request id
      #     prId =
      #     # disable line below to merge manually
      #     # auto-merging pull-request
      #     gh pr merge $prId --auto -m
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
